version: '3'
services:
  app:
    image: monapp:1.0
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: db:1.0
    environment:
      MYSQL_ROOT_PASSWORD: 0000
    ports:
      - "3305:3305"
